export type Airport = {
  code: string;
  name: string;
  country: string;
  location: string;
};

export const COUNTRY_ALPHA3: Record<string, string> = {
  프랑스: 'FRA',
  태국: 'THA',
  체코: 'CZE',
  대한민국: 'KOR',
  미국: 'USA',
  일본: 'JPN',
  중국: 'CHN',
  홍콩: 'HKG',
  마카오: 'MAC',
  대만: 'TWN',
  베트남: 'VNM',
  싱가포르: 'SGP',
  필리핀: 'PHL',
  말레이시아: 'MYS',
  인도네시아: 'IDN',
  캄보디아: 'KHM',
  인도: 'IND',
  캐나다: 'CAN',
  멕시코: 'MEX',
  영국: 'GBR',
  독일: 'DEU',
  이탈리아: 'ITA',
  스페인: 'ESP',
  네덜란드: 'NLD',
  스위스: 'CHE',
  오스트리아: 'AUT',
  포르투갈: 'PRT',
  그리스: 'GRC',
  튀르키예: 'TUR',
  아랍에미리트: 'ARE',
  카타르: 'QAT',
  호주: 'AUS',
  뉴질랜드: 'NZL',
  괌: 'GUM',
};

export const AIRPORTS: Airport[] = [
  {
    code: 'CDG',
    name: '파리샤를드골',
    country: '프랑스',
    location: '프랑스 / 파리',
  },
  {
    code: 'ORY',
    name: '파리오를리',
    country: '프랑스',
    location: '프랑스 / 파리',
  },
  {
    code: 'BVA',
    name: '파리부바이스',
    country: '프랑스',
    location: '프랑스 / 파리',
  },
  { code: 'HKT', name: '푸켓', country: '태국', location: '태국 / 푸켓' },
  {
    code: 'BKK',
    name: '방콕수완나품',
    country: '태국',
    location: '태국 / 방콕',
  },
  {
    code: 'DMK',
    name: '방콕돈므앙',
    country: '태국',
    location: '태국 / 방콕',
  },
  {
    code: 'CNX',
    name: '치앙마이',
    country: '태국',
    location: '태국 / 치앙마이',
  },
  { code: 'PRG', name: '프라하', country: '체코', location: '체코 / 프라하' },
  {
    code: 'ICN',
    name: '인천',
    country: '대한민국',
    location: '서울 / 인천',
  },
  {
    code: 'GMP',
    name: '김포',
    country: '대한민국',
    location: '서울 / 김포',
  },
  {
    code: 'PUS',
    name: '김해',
    country: '대한민국',
    location: '부산 / 김해',
  },
  {
    code: 'CJU',
    name: '제주',
    country: '대한민국',
    location: '제주 / 제주',
  },
  {
    code: 'JFK',
    name: '뉴욕존에프케네디',
    country: '미국',
    location: '미국 / 뉴욕',
  },
  {
    code: 'EWR',
    name: '뉴어크',
    country: '미국',
    location: '미국 / 뉴욕',
  },
  {
    code: 'LAX',
    name: '로스앤젤레스',
    country: '미국',
    location: '미국 / 로스앤젤레스',
  },
  {
    code: 'SFO',
    name: '샌프란시스코',
    country: '미국',
    location: '미국 / 샌프란시스코',
  },
  {
    code: 'SEA',
    name: '시애틀타코마',
    country: '미국',
    location: '미국 / 시애틀',
  },
  {
    code: 'ORD',
    name: '시카고오헤어',
    country: '미국',
    location: '미국 / 시카고',
  },
  {
    code: 'LAS',
    name: '라스베이거스',
    country: '미국',
    location: '미국 / 라스베이거스',
  },
  {
    code: 'HNL',
    name: '호놀룰루',
    country: '미국',
    location: '미국 / 하와이',
  },
  {
    code: 'YVR',
    name: '밴쿠버',
    country: '캐나다',
    location: '캐나다 / 밴쿠버',
  },
  {
    code: 'YYZ',
    name: '토론토피어슨',
    country: '캐나다',
    location: '캐나다 / 토론토',
  },
  {
    code: 'MEX',
    name: '멕시코시티',
    country: '멕시코',
    location: '멕시코 / 멕시코시티',
  },
  { code: 'NRT', name: '나리타', country: '일본', location: '일본 / 도쿄' },
  { code: 'HND', name: '하네다', country: '일본', location: '일본 / 도쿄' },
  { code: 'KIX', name: '간사이', country: '일본', location: '일본 / 오사카' },
  {
    code: 'CTS',
    name: '신치토세',
    country: '일본',
    location: '일본 / 삿포로',
  },
  {
    code: 'NGO',
    name: '주부센트레아',
    country: '일본',
    location: '일본 / 나고야',
  },
  { code: 'FUK', name: '후쿠오카', country: '일본', location: '일본 / 후쿠오카' },
  { code: 'OKA', name: '나하', country: '일본', location: '일본 / 오키나와' },
  {
    code: 'PEK',
    name: '베이징서우두',
    country: '중국',
    location: '중국 / 베이징',
  },
  {
    code: 'PVG',
    name: '상하이푸둥',
    country: '중국',
    location: '중국 / 상하이',
  },
  {
    code: 'SHA',
    name: '상하이훙차오',
    country: '중국',
    location: '중국 / 상하이',
  },
  {
    code: 'CAN',
    name: '광저우바이윈',
    country: '중국',
    location: '중국 / 광저우',
  },
  {
    code: 'SZX',
    name: '선전바오안',
    country: '중국',
    location: '중국 / 선전',
  },
  {
    code: 'CTU',
    name: '청두솽류',
    country: '중국',
    location: '중국 / 청두',
  },
  {
    code: 'HKG',
    name: '홍콩첵랍콕',
    country: '홍콩',
    location: '홍콩 / 홍콩',
  },
  {
    code: 'MFM',
    name: '마카오',
    country: '마카오',
    location: '마카오 / 마카오',
  },
  {
    code: 'TPE',
    name: '타이베이타오위안',
    country: '대만',
    location: '대만 / 타이베이',
  },
  {
    code: 'KHH',
    name: '가오슝',
    country: '대만',
    location: '대만 / 가오슝',
  },
  {
    code: 'HAN',
    name: '하노이노이바이',
    country: '베트남',
    location: '베트남 / 하노이',
  },
  {
    code: 'SGN',
    name: '호치민떤선녓',
    country: '베트남',
    location: '베트남 / 호치민',
  },
  {
    code: 'DAD',
    name: '다낭',
    country: '베트남',
    location: '베트남 / 다낭',
  },
  {
    code: 'SIN',
    name: '싱가포르창이',
    country: '싱가포르',
    location: '싱가포르 / 싱가포르',
  },
  {
    code: 'MNL',
    name: '마닐라니노이아키노',
    country: '필리핀',
    location: '필리핀 / 마닐라',
  },
  {
    code: 'CEB',
    name: '세부막탄',
    country: '필리핀',
    location: '필리핀 / 세부',
  },
  {
    code: 'KUL',
    name: '쿠알라룸푸르',
    country: '말레이시아',
    location: '말레이시아 / 쿠알라룸푸르',
  },
  {
    code: 'DPS',
    name: '발리응우라라이',
    country: '인도네시아',
    location: '인도네시아 / 발리',
  },
  {
    code: 'CGK',
    name: '자카르타수카르노하타',
    country: '인도네시아',
    location: '인도네시아 / 자카르타',
  },
  {
    code: 'PNH',
    name: '프놈펜',
    country: '캄보디아',
    location: '캄보디아 / 프놈펜',
  },
  {
    code: 'REP',
    name: '시엠립앙코르',
    country: '캄보디아',
    location: '캄보디아 / 시엠립',
  },
  {
    code: 'DEL',
    name: '델리인디라간디',
    country: '인도',
    location: '인도 / 델리',
  },
  {
    code: 'BOM',
    name: '뭄바이차트라파티시바지',
    country: '인도',
    location: '인도 / 뭄바이',
  },
  {
    code: 'LHR',
    name: '런던히드로',
    country: '영국',
    location: '영국 / 런던',
  },
  {
    code: 'LGW',
    name: '런던개트윅',
    country: '영국',
    location: '영국 / 런던',
  },
  {
    code: 'FRA',
    name: '프랑크푸르트',
    country: '독일',
    location: '독일 / 프랑크푸르트',
  },
  {
    code: 'MUC',
    name: '뮌헨',
    country: '독일',
    location: '독일 / 뮌헨',
  },
  {
    code: 'FCO',
    name: '로마피우미치노',
    country: '이탈리아',
    location: '이탈리아 / 로마',
  },
  {
    code: 'MXP',
    name: '밀라노말펜사',
    country: '이탈리아',
    location: '이탈리아 / 밀라노',
  },
  {
    code: 'MAD',
    name: '마드리드바라하스',
    country: '스페인',
    location: '스페인 / 마드리드',
  },
  {
    code: 'BCN',
    name: '바르셀로나',
    country: '스페인',
    location: '스페인 / 바르셀로나',
  },
  {
    code: 'AMS',
    name: '암스테르담스히폴',
    country: '네덜란드',
    location: '네덜란드 / 암스테르담',
  },
  {
    code: 'ZRH',
    name: '취리히',
    country: '스위스',
    location: '스위스 / 취리히',
  },
  {
    code: 'VIE',
    name: '빈',
    country: '오스트리아',
    location: '오스트리아 / 빈',
  },
  {
    code: 'LIS',
    name: '리스본',
    country: '포르투갈',
    location: '포르투갈 / 리스본',
  },
  {
    code: 'ATH',
    name: '아테네',
    country: '그리스',
    location: '그리스 / 아테네',
  },
  {
    code: 'IST',
    name: '이스탄불',
    country: '튀르키예',
    location: '튀르키예 / 이스탄불',
  },
  {
    code: 'DXB',
    name: '두바이',
    country: '아랍에미리트',
    location: '아랍에미리트 / 두바이',
  },
  {
    code: 'AUH',
    name: '아부다비',
    country: '아랍에미리트',
    location: '아랍에미리트 / 아부다비',
  },
  {
    code: 'DOH',
    name: '도하하마드',
    country: '카타르',
    location: '카타르 / 도하',
  },
  {
    code: 'SYD',
    name: '시드니킹스퍼드스미스',
    country: '호주',
    location: '호주 / 시드니',
  },
  {
    code: 'MEL',
    name: '멜버른',
    country: '호주',
    location: '호주 / 멜버른',
  },
  {
    code: 'BNE',
    name: '브리즈번',
    country: '호주',
    location: '호주 / 브리즈번',
  },
  {
    code: 'AKL',
    name: '오클랜드',
    country: '뉴질랜드',
    location: '뉴질랜드 / 오클랜드',
  },
  {
    code: 'GUM',
    name: '괌원팟',
    country: '괌',
    location: '괌 / 괌',
  },
];
